### ISSUE TITLE
SAE问题

### ISSUE THREAD

**Issue by xialang2012** [vfhky/SCS#1]
SAE typecho上面

> 404 - 页面没找到
> 
> 你想查看的页面已被转移或删除了, 要不要搜索看看:

**Comment by vfhky** [comment]
刚在自己的SAE（ http://1.vfhky.applinzi.com/index.php/archives/19/ ） 上试了下是正常的。请问你的是插件没安装成功还是安装成功了，但是不能上传图片到SCS上？

**Comment by xialang2012** [comment]
已经搞定了，我的操作有问题

**Comment by vfhky** [comment]
ok。
